function photoDB(){return new Promise((res,rej)=>{const req=indexedDB.open(PHOTO_DB,1);req.onupgradeneeded=()=>{const d=req.result;if(!d.objectStoreNames.contains('photos'))d.createObjectStore('photos',{keyPath:'id'})};req.onsuccess=()=>res(req.result);req.onerror=()=>rej(req.error)})}
async function savePhotoFiles(jobId,kind,fileList){if(!fileList||!fileList.length)return;const files=[...fileList].slice(0,12);const d=await photoDB();const tx=d.transaction('photos','readwrite'),st=tx.objectStore('photos');files.forEach((file,i)=>st.put({id:`${jobId}:${kind}:${Date.now()}:${i}`,jobId,kind,file}));await new Promise(r=>tx.oncomplete=r);if(window.CCCloud?.configured){try{const paths=await CCCloud.uploadJobPhotos(jobId,kind,files);const j=db.jobs.find(x=>x.id===jobId);if(j&&paths.length){j.cloudPhotos=j.cloudPhotos||{before:[],after:[]};j.cloudPhotos[kind]=[...(j.cloudPhotos[kind]||[]),...paths];save()}}catch(e){console.warn('Cloud photo upload failed; local copy was still saved.',e)}}}
async function getPhotos(jobId,kind){const d=await photoDB();return new Promise((res,rej)=>{const tx=d.transaction('photos','readonly'),rq=tx.objectStore('photos').getAll();rq.onsuccess=()=>res(rq.result.filter(x=>x.jobId===jobId&&x.kind===kind));rq.onerror=()=>rej(rq.error)})}
async function renderStoredPhotos(jobId,kind,target){const rows=await getPhotos(jobId,kind),box=el(target);box.innerHTML='';rows.forEach(r=>{const img=document.createElement('img');img.src=URL.createObjectURL(r.file);img.alt=kind+' job photo';box.appendChild(img)})}
async function deleteJobPhotos(jobId){const d=await photoDB();const all=await new Promise((res,rej)=>{const tx=d.transaction('photos','readonly'),rq=tx.objectStore('photos').getAll();rq.onsuccess=()=>res(rq.result);rq.onerror=()=>rej(rq.error)});const tx=d.transaction('photos','readwrite'),st=tx.objectStore('photos');all.filter(x=>x.jobId===jobId).forEach(x=>st.delete(x.id));return new Promise(r=>tx.oncomplete=r)}

function loadScript(src){return new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=src;s.onload=resolve;s.onerror=reject;document.head.appendChild(s)})}
async function initCloud(){
  try{
    await loadScript('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2');
    await loadScript('supabase-config.js');
    await loadScript('cloud.js');
    if(!window.CCCloud?.configured)return;
    const cloudNote=document.createElement('div');cloudNote.id='cloudStatus';cloudNote.className='notice';cloudNote.style.margin='0 0 16px';cloudNote.textContent='Cloud connected. Sign in below to sync business data across devices.';el('loginBox').prepend(cloudNote);
    const cloudFields=document.createElement('div');cloudFields.innerHTML=`<div class="grid"><div class="field"><label>Cloud email</label><input id="cloudEmail" type="email" autocomplete="username"></div><div class="field"><label>Cloud password</label><input id="cloudPassword" type="password" autocomplete="current-password"></div></div><div class="actions"><button type="button" id="cloudLoginBtn" class="btn dark">Cloud Sign In</button></div>`;el('loginBox').insertBefore(cloudFields,el('loginBox').querySelector('.hint'));
    el('cloudLoginBtn').addEventListener('click',async()=>{const email=el('cloudEmail').value.trim(),password=el('cloudPassword').value;if(!email||!password){alert('Enter your Supabase owner email and password.');return}const {error}=await CCCloud.client.auth.signInWithPassword({email,password});if(error){alert(error.message);return}db=merge(clone(DEFAULTS),await CCCloud.loadDb(db));save();sessionStorage.setItem('cc_auth','1');openDashboard();el('cloudStatus').textContent='Cloud signed in and synced.'});
    const {data:{session}}=await CCCloud.client.auth.getSession();if(session){db=merge(clone(DEFAULTS),await CCCloud.loadDb(db));save();}
    setInterval(()=>CCCloud.syncDb(db).catch(console.warn),5000);
    el('saveRequest').addEventListener('click',async()=>{if(!currentQuote)return;try{const result=await CCCloud.submitQuote(currentQuote,el('qPhotoInput').files);if(result.ok){currentQuote.cloudPhotos=result.paths||[];el('saveMessage').textContent='Quote submitted to Clean & Cut successfully.';el('saveMessage').classList.remove('hidden')}}catch(e){console.error(e);el('saveMessage').textContent='The quote saved on this device, but cloud submission failed. Please email the request too.';el('saveMessage').classList.remove('hidden')}});
  }catch(e){console.warn('Cloud module did not load. Local mode remains available.',e)}
}

renderChoices();showStep(1);initCloud();